name: Test EXE in clean Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    runs-on: windows-latest   # 微软官方最新 Windows Server 镜像

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the executable
        run: .\Launcher-new.exe
